In [55]:
import torch as T
import copy


def symmetric_difference(l:list)->list:
    sym_dif_list = []
    for i in range(len(l)-1):
        a = l[i]
        b = l[i+1]
        sym_dif = a.to(dtype=bool)
        sym_dif[T.eq(a,b)] = False
        sym_dif_list.append(sym_dif)
    return sym_dif_list

listing = []
snake = T.ones((8,))
for i in range(8):
    alpha = copy.deepcopy(snake)
    alpha[:i] = 0
    listing.append(alpha)
    print(listing[i])
snake = alpha

dif = symmetric_difference(listing)
dif.reverse()
init = -1
for d in dif:
    snake[d] = init
    init -= 1
    print(snake)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 0., 1., 1., 1., 1., 1., 1.])
tensor([0., 0., 0., 1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0., 1., 1.])
tensor([0., 0., 0., 0., 0., 0., 0., 1.])
tensor([ 0.,  0.,  0.,  0.,  0.,  0., -1.,  1.])
tensor([ 0.,  0.,  0.,  0.,  0., -2., -1.,  1.])
tensor([ 0.,  0.,  0.,  0., -3., -2., -1.,  1.])
tensor([ 0.,  0.,  0., -4., -3., -2., -1.,  1.])
tensor([ 0.,  0., -5., -4., -3., -2., -1.,  1.])
tensor([ 0., -6., -5., -4., -3., -2., -1.,  1.])
tensor([-7., -6., -5., -4., -3., -2., -1.,  1.])


In [ ]:
[,],    [,],    [,],    [,]
[,],[,],[,],[,],[,],[,],[,],[,]